<a href="https://colab.research.google.com/github/maps-05/portfolio/blob/main/DataScrapingandAnalysis_nba_standing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NBA Team Standings Data Scraping and Analysis

Name: **RELATIVO, Muffle P.**

Section: **IE**

In [ ]:
import pandas as pd
import numpy as np
import requests
import warnings
import matplotlib.pyplot as plt
import seaborn as sns
from bs4 import BeautifulSoup

warnings.filterwarnings("ignore")

In [ ]:
# URL
url = 'https://www.cbssports.com/nba/standings'

# Send requests
headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/134.0.0.0 Safari/537.36'}

# Response
response = requests.get(url = url, headers = headers)

# Create a bs4 object to parse the HTML content
soup = BeautifulSoup(response.content, 'html.parser')

# **EASTERN CONFERENCE**

In [ ]:
# Find the tbody containing Eastern Conference Teams, you can use select('tbody')[0], means first tbody found

tbody = soup.select('tbody')[0]

In [ ]:
# Team names in Eatern Conference

team = []

if tbody:
    for i in tbody.find_all('a'):
        text = i.get_text().strip()
        if text:
            team.append(text)

print(team)

['Cleveland', 'Boston', 'New York', 'Milwaukee', 'Indiana', 'Detroit', 'Atlanta', 'Orlando', 'Miami', 'Chicago', 'Toronto', 'Brooklyn', 'Philadelphia', 'Charlotte', 'Washington']

In [ ]:
# Data for Eastern Conference

data = []
for row in tbody.find_all('tr'):
    col = row.find_all('td')
    col = [ele.text.strip() for ele in col]
    data.append([ele for ele in col if ele])
data = pd.DataFrame(data, columns = ['No.', 'Team', 'W', 'L', 'PCT', 'GB', 'PPG', 'OPPG', 'DIFF', 'HOME', 'ROAD', 'DIV', 'CONF', 'STRK', 'L10', 'W', 'DIV', 'POST'])

print(data)

   No.           Team   W   L   PCT    GB    PPG   OPPG   DIFF   HOME   ROAD  \
0    1  Cleveland - y  55  10  .846     —  122.7  111.4   11.3   30-4   25-6
1    2         Boston  47  19  .712   8.5  116.8  108.3    8.5  23-12   24-7
2    3       New York  42  23  .646  13.0  117.1  112.7    4.4  21-11  21-12
3    4      Milwaukee  36  28  .563  18.5  114.6  112.5    2.1  22-11  14-17
4    5        Indiana  36  28  .563  18.5  116.4  115.4    1.0  20-10  16-18
5    6        Detroit  37  29  .561  18.5  114.8  112.9    1.9  18-14  19-15
6    7        Atlanta  32  34  .485  23.5  117.4  119.6   -2.2  17-16  15-18
7    8        Orlando  30  36  .455  25.5  104.3  106.1   -1.8  18-16  12-20
8    9          Miami  29  36  .446  26.0  109.9  110.6   -0.7  15-16  14-20
9   10        Chicago  27  38  .415  28.0  116.6  120.3   -3.7  12-22  15-16
10  11        Toronto  23  43  .348  32.5  110.8  115.7   -4.9  16-20   7-23
11  12       Brooklyn  22  43  .338  33.0  105.2  111.5   -6.3  10-21  12-22
12  13   Philadelphia  22  43  .338  33.0  109.4  114.4   -5.0  12-21  10-22
13  14      Charlotte  16  49  .246  39.0  105.4  113.0   -7.6  10-24   6-25
14  15     Washington  13  51  .203  41.5  108.3  120.6  -12.3   7-26   6-25

     DIV   CONF STRK   L10     W     DIV    POST
0   11-1   38-7  W15  10-0  62.9  100.0%  100.0%
1   11-2  32-11   L1   7-3  59.7   98.5%  100.0%
2   10-3  28-13   W2   5-5  52.2    1.5%  100.0%
3    6-7  26-19   L3   6-4  43.9    0.0%   88.5%
4    8-5  21-20   W1   5-5  46.0    0.0%   98.0%
5    4-9  25-20   W2   7-3  42.8    0.0%   88.6%
6    8-4  24-18   W4   6-4  39.0   45.7%   73.4%
7    8-3  24-20   L1   3-7  38.2   24.5%   60.9%
8    7-5  18-22   L5   3-7  38.5   29.8%   60.6%
9   4-11  22-23   W3   5-5  31.7    0.0%    3.1%
10   5-8  15-29   W2   6-4  28.2    0.0%   <1.0%
11   3-8  12-28   L1   2-8  31.0    0.0%    2.4%
12  3-11  14-27   L2   2-8  33.9    0.0%   23.6%
13  1-12   9-33   L1   2-8  24.1    0.0%   <1.0%
14   6-6  10-28   L2   4-6  15.6    0.0%    0.0%

In [ ]:
# Data Frame for Eastern Conference

team_df = pd.DataFrame(team, columns = ['Team'])
team_df

            Team
0      Cleveland
1         Boston
2       New York
3      Milwaukee
4        Indiana
5        Detroit
6        Atlanta
7        Orlando
8          Miami
9        Chicago
10       Toronto
11      Brooklyn
12  Philadelphia
13     Charlotte
14    Washington

In [ ]:
#  Data Frame for Eastern Conference

team_data = pd.DataFrame(data).iloc[:, 2:]
team_data

,W,L,PCT,GB,PPG,OPPG,DIFF,HOME,ROAD,DIV,CONF,STRK,L10,W,DIV,POST
0,55,10,.846,—,122.7,111.4,11.3,30-4,25-6,11-1,38-7,W15,10-0,62.9,100.0%,100.0%
1,47,19,.712,8.5,116.8,108.3,8.5,23-12,24-7,11-2,32-11,L1,7-3,59.7,98.5%,100.0%
2,42,23,.646,13.0,117.1,112.7,4.4,21-11,21-12,10-3,28-13,W2,5-5,52.2,1.5%,100.0%
3,36,28,.563,18.5,114.6,112.5,2.1,22-11,14-17,6-7,26-19,L3,6-4,43.9,0.0%,88.5%
4,36,28,.563,18.5,116.4,115.4,1.0,20-10,16-18,8-5,21-20,W1,5-5,46.0,0.0%,98.0%
5,37,29,.561,18.5,114.8,112.9,1.9,18-14,19-15,4-9,25-20,W2,7-3,42.8,0.0%,88.6%
6,32,34,.485,23.5,117.4,119.6,-2.2,17-16,15-18,8-4,24-18,W4,6-4,39.0,45.7%,73.4%
7,30,36,.455,25.5,104.3,106.1,-1.8,18-16,12-20,8-3,24-20,L1,3-7,38.2,24.5%,60.9%
8,29,36,.446,26.0,109.9,110.6,-0.7,15-16,14-20,7-5,18-22,L5,3-7,38.5,29.8%,60.6%
9,27,38,.415,28.0,116.6,120.3,-3.7,12-22,15-16,4-11,22-23,W3,5-5,31.7,0.0%,3.1%
10,23,43,.348,32.5,110.8,115.7,-4.9,16-20,7-23,5-8,15-29,W2,6-4,28.2,0.0%,<1.0%
11,22,43,.338,33.0,105.2,111.5,-6.3,10-21,12-22,3-8,12-28,L1,2-8,31.0,0.0%,2.4%
12,22,43,.338,33.0,109.4,114.4,-5.0,12-21,10-22,3-11,14-27,L2,2-8,33.9,0.0%,23.6%
13,16,49,.246,39.0,105.4,113.0,-7.6,10-24,6-25,1-12,9-33,L1,2-8,24.1,0.0%,<1.0%
14,13,51,.203,41.5,108.3,120.6,-12.3,7-26,6-25,6-6,10-28,L2,4-6,15.6,0.0%,0.0%

In [ ]:
# Combine both Data Frame (Eastern Conference)

df_final = pd.concat([team_df, team_data], axis = 1)
df_final

,Team,W,L,PCT,GB,PPG,OPPG,DIFF,HOME,ROAD,DIV,CONF,STRK,L10,W,DIV,POST
0,Cleveland,55,10,.846,—,122.7,111.4,11.3,30-4,25-6,11-1,38-7,W15,10-0,62.9,100.0%,100.0%
1,Boston,47,19,.712,8.5,116.8,108.3,8.5,23-12,24-7,11-2,32-11,L1,7-3,59.7,98.5%,100.0%
2,New York,42,23,.646,13.0,117.1,112.7,4.4,21-11,21-12,10-3,28-13,W2,5-5,52.2,1.5%,100.0%
3,Milwaukee,36,28,.563,18.5,114.6,112.5,2.1,22-11,14-17,6-7,26-19,L3,6-4,43.9,0.0%,88.5%
4,Indiana,36,28,.563,18.5,116.4,115.4,1.0,20-10,16-18,8-5,21-20,W1,5-5,46.0,0.0%,98.0%
5,Detroit,37,29,.561,18.5,114.8,112.9,1.9,18-14,19-15,4-9,25-20,W2,7-3,42.8,0.0%,88.6%
6,Atlanta,32,34,.485,23.5,117.4,119.6,-2.2,17-16,15-18,8-4,24-18,W4,6-4,39.0,45.7%,73.4%
7,Orlando,30,36,.455,25.5,104.3,106.1,-1.8,18-16,12-20,8-3,24-20,L1,3-7,38.2,24.5%,60.9%
8,Miami,29,36,.446,26.0,109.9,110.6,-0.7,15-16,14-20,7-5,18-22,L5,3-7,38.5,29.8%,60.6%
9,Chicago,27,38,.415,28.0,116.6,120.3,-3.7,12-22,15-16,4-11,22-23,W3,5-5,31.7,0.0%,3.1%
10,Toronto,23,43,.348,32.5,110.8,115.7,-4.9,16-20,7-23,5-8,15-29,W2,6-4,28.2,0.0%,<1.0%
11,Brooklyn,22,43,.338,33.0,105.2,111.5,-6.3,10-21,12-22,3-8,12-28,L1,2-8,31.0,0.0%,2.4%
12,Philadelphia,22,43,.338,33.0,109.4,114.4,-5.0,12-21,10-22,3-11,14-27,L2,2-8,33.9,0.0%,23.6%
13,Charlotte,16,49,.246,39.0,105.4,113.0,-7.6,10-24,6-25,1-12,9-33,L1,2-8,24.1,0.0%,<1.0%
14,Washington,13,51,.203,41.5,108.3,120.6,-12.3,7-26,6-25,6-6,10-28,L2,4-6,15.6,0.0%,0.0%

# **WESTERN CONFERENCE**

In [ ]:
# Find the table containing (Western Conference Teams), you can use select('tbody')[1], means second tbody found

tbody1 = soup.select('tbody')[1]

In [ ]:
# Team names in Western Conference

team = []

if tbody1:
    for i in tbody1.find_all('a'):
        text = i.get_text().strip()
        if text:
            team.append(text)

print(team)

['Oklahoma City', 'Memphis', 'Denver', 'L.A. Lakers', 'Houston', 'Golden St.', 'Minnesota', 'L.A. Clippers', 'Sacramento', 'Dallas', 'Phoenix', 'San Antonio', 'Portland', 'New Orleans', 'Utah']

In [ ]:
# Data for Western Conference

data = []

for row in tbody1.find_all('tr'):
    col = row.find_all('td')
    col = [ele.text.strip() for ele in col]
    data.append([ele for ele in col if ele])
data = pd.DataFrame(data, columns = ['No.', 'Team', 'W', 'L', 'PCT', 'GB', 'PPG', 'OPPG', 'DIFF', 'HOME', 'ROAD', 'DIV', 'CONF', 'STRK', 'L10', 'W', 'DIV', 'POST'])

print(data)

   No.               Team   W   L   PCT    GB    PPG   OPPG  DIFF   HOME  \
0    1  Oklahoma City - x  54  12  .818     —  119.7  107.2  12.5   29-5
1    2            Memphis  42  24  .636  12.0  122.6  116.7   5.9  24-10
2    3             Denver  42  24  .636  12.0  121.1  116.6   4.5  22-10
3    4        L.A. Lakers  40  23  .635  12.5  112.9  111.1   1.8   25-7
4    5            Houston  41  25  .621  13.0  112.9  108.8   4.1  23-10
5    6         Golden St.  37  28  .569  16.5  113.6  111.3   2.3  19-13
6    7          Minnesota  38  29  .567  16.5  112.9  109.0   3.9  18-14
7    8      L.A. Clippers  36  30  .545  18.0  111.1  108.9   2.2  22-10
8    9         Sacramento  33  31  .516  20.0  116.6  115.2   1.4  16-15
9   10             Dallas  33  34  .493  21.5  114.8  114.6   0.2  19-15
10  11            Phoenix  30  36  .455  24.0  114.3  116.4  -2.1  18-13
11  12        San Antonio  27  37  .422  26.0  113.8  116.1  -2.3  16-16
12  13           Portland  28  39  .418  26.5  110.6  114.6  -4.0  16-16
13  14        New Orleans  18  48  .273  36.0  111.0  119.1  -8.1  12-21
14  15           Utah - e  15  51  .227  39.0  112.5  119.8  -7.3   8-24

     ROAD   DIV   CONF STRK  L10     W     DIV    POST
0    25-7  11-4  32-11   W1  8-2  66.1  100.0%  100.0%
1   18-14  10-5  25-16   W4  5-5  52.0   78.1%   99.8%
2   20-14   7-6  25-15   L1  5-5  52.8    0.0%  100.0%
3   15-16  11-3  27-12   L2  8-2  46.1   38.6%   78.4%
4   18-15  12-3  25-16   W4  6-4  48.7   21.5%   94.4%
5   18-15  2-10  21-19   W5  9-1  44.6   11.8%   65.0%
6   20-15   8-5  27-18   W6  7-3  45.8    0.0%   78.9%
7   14-20   7-7  21-22   W1  5-5  46.8   47.9%   85.7%
8   17-16   4-8  23-21   L2  5-5  41.7    1.7%   31.5%
9   14-19   8-6  23-24   L1  2-8  43.8    0.0%   61.3%
10  12-23   8-4  20-24   L2  3-7  37.7    0.0%    3.5%
11  11-21  4-11  19-25   W1  3-7  35.9    0.0%   <1.0%
12  12-23   5-9  15-30   L5  4-6  32.4    0.0%    0.0%
13   6-27  3-12  12-32   W1  5-5  24.7    0.0%    0.0%
14   7-27   2-9   7-37   L7  1-9  24.3    0.0%    0.0%

In [ ]:
# Data Frame for Western Conference

team_df2 = pd.DataFrame(team, columns = ['Team'])
team_df2

             Team
0   Oklahoma City
1         Memphis
2          Denver
3     L.A. Lakers
4         Houston
5      Golden St.
6       Minnesota
7   L.A. Clippers
8      Sacramento
9          Dallas
10        Phoenix
11    San Antonio
12       Portland
13    New Orleans
14           Utah

In [ ]:
#  Data Frame for Western Conference

team_data2 = pd.DataFrame(data).iloc[:, 2:]
team_data2

,W,L,PCT,GB,PPG,OPPG,DIFF,HOME,ROAD,DIV,CONF,STRK,L10,W,DIV,POST
0,54,12,.818,—,119.7,107.2,12.5,29-5,25-7,11-4,32-11,W1,8-2,66.1,100.0%,100.0%
1,42,24,.636,12.0,122.6,116.7,5.9,24-10,18-14,10-5,25-16,W4,5-5,52.0,78.1%,99.8%
2,42,24,.636,12.0,121.1,116.6,4.5,22-10,20-14,7-6,25-15,L1,5-5,52.8,0.0%,100.0%
3,40,23,.635,12.5,112.9,111.1,1.8,25-7,15-16,11-3,27-12,L2,8-2,46.1,38.6%,78.4%
4,41,25,.621,13.0,112.9,108.8,4.1,23-10,18-15,12-3,25-16,W4,6-4,48.7,21.5%,94.4%
5,37,28,.569,16.5,113.6,111.3,2.3,19-13,18-15,2-10,21-19,W5,9-1,44.6,11.8%,65.0%
6,38,29,.567,16.5,112.9,109.0,3.9,18-14,20-15,8-5,27-18,W6,7-3,45.8,0.0%,78.9%
7,36,30,.545,18.0,111.1,108.9,2.2,22-10,14-20,7-7,21-22,W1,5-5,46.8,47.9%,85.7%
8,33,31,.516,20.0,116.6,115.2,1.4,16-15,17-16,4-8,23-21,L2,5-5,41.7,1.7%,31.5%
9,33,34,.493,21.5,114.8,114.6,0.2,19-15,14-19,8-6,23-24,L1,2-8,43.8,0.0%,61.3%
10,30,36,.455,24.0,114.3,116.4,-2.1,18-13,12-23,8-4,20-24,L2,3-7,37.7,0.0%,3.5%
11,27,37,.422,26.0,113.8,116.1,-2.3,16-16,11-21,4-11,19-25,W1,3-7,35.9,0.0%,<1.0%
12,28,39,.418,26.5,110.6,114.6,-4.0,16-16,12-23,5-9,15-30,L5,4-6,32.4,0.0%,0.0%
13,18,48,.273,36.0,111.0,119.1,-8.1,12-21,6-27,3-12,12-32,W1,5-5,24.7,0.0%,0.0%
14,15,51,.227,39.0,112.5,119.8,-7.3,8-24,7-27,2-9,7-37,L7,1-9,24.3,0.0%,0.0%

In [ ]:
# Combine both Data Frame (Western Conference)

df_final2 = pd.concat([team_df2, team_data2], axis = 1)
df_final2

,Team,W,L,PCT,GB,PPG,OPPG,DIFF,HOME,ROAD,DIV,CONF,STRK,L10,W,DIV,POST
0,Oklahoma City,54,12,.818,—,119.7,107.2,12.5,29-5,25-7,11-4,32-11,W1,8-2,66.1,100.0%,100.0%
1,Memphis,42,24,.636,12.0,122.6,116.7,5.9,24-10,18-14,10-5,25-16,W4,5-5,52.0,78.1%,99.8%
2,Denver,42,24,.636,12.0,121.1,116.6,4.5,22-10,20-14,7-6,25-15,L1,5-5,52.8,0.0%,100.0%
3,L.A. Lakers,40,23,.635,12.5,112.9,111.1,1.8,25-7,15-16,11-3,27-12,L2,8-2,46.1,38.6%,78.4%
4,Houston,41,25,.621,13.0,112.9,108.8,4.1,23-10,18-15,12-3,25-16,W4,6-4,48.7,21.5%,94.4%
5,Golden St.,37,28,.569,16.5,113.6,111.3,2.3,19-13,18-15,2-10,21-19,W5,9-1,44.6,11.8%,65.0%
6,Minnesota,38,29,.567,16.5,112.9,109.0,3.9,18-14,20-15,8-5,27-18,W6,7-3,45.8,0.0%,78.9%
7,L.A. Clippers,36,30,.545,18.0,111.1,108.9,2.2,22-10,14-20,7-7,21-22,W1,5-5,46.8,47.9%,85.7%
8,Sacramento,33,31,.516,20.0,116.6,115.2,1.4,16-15,17-16,4-8,23-21,L2,5-5,41.7,1.7%,31.5%
9,Dallas,33,34,.493,21.5,114.8,114.6,0.2,19-15,14-19,8-6,23-24,L1,2-8,43.8,0.0%,61.3%
10,Phoenix,30,36,.455,24.0,114.3,116.4,-2.1,18-13,12-23,8-4,20-24,L2,3-7,37.7,0.0%,3.5%
11,San Antonio,27,37,.422,26.0,113.8,116.1,-2.3,16-16,11-21,4-11,19-25,W1,3-7,35.9,0.0%,<1.0%
12,Portland,28,39,.418,26.5,110.6,114.6,-4.0,16-16,12-23,5-9,15-30,L5,4-6,32.4,0.0%,0.0%
13,New Orleans,18,48,.273,36.0,111.0,119.1,-8.1,12-21,6-27,3-12,12-32,W1,5-5,24.7,0.0%,0.0%
14,Utah,15,51,.227,39.0,112.5,119.8,-7.3,8-24,7-27,2-9,7-37,L7,1-9,24.3,0.0%,0.0%

# **COMBINED DATA FOR EATERN AND WESTERN CONFERENCE**

In [ ]:
# Combine Eastern and Western Conference Data via pd.concat

df_combined = pd.concat([df_final, df_final2], axis = 0)
df_combined

,Team,W,L,PCT,GB,PPG,OPPG,DIFF,HOME,ROAD,DIV,CONF,STRK,L10,W,DIV,POST
0,Cleveland,55,10,.846,—,122.7,111.4,11.3,30-4,25-6,11-1,38-7,W15,10-0,62.9,100.0%,100.0%
1,Boston,47,19,.712,8.5,116.8,108.3,8.5,23-12,24-7,11-2,32-11,L1,7-3,59.7,98.5%,100.0%
2,New York,42,23,.646,13.0,117.1,112.7,4.4,21-11,21-12,10-3,28-13,W2,5-5,52.2,1.5%,100.0%
3,Milwaukee,36,28,.563,18.5,114.6,112.5,2.1,22-11,14-17,6-7,26-19,L3,6-4,43.9,0.0%,88.5%
4,Indiana,36,28,.563,18.5,116.4,115.4,1.0,20-10,16-18,8-5,21-20,W1,5-5,46.0,0.0%,98.0%
5,Detroit,37,29,.561,18.5,114.8,112.9,1.9,18-14,19-15,4-9,25-20,W2,7-3,42.8,0.0%,88.6%
6,Atlanta,32,34,.485,23.5,117.4,119.6,-2.2,17-16,15-18,8-4,24-18,W4,6-4,39.0,45.7%,73.4%
7,Orlando,30,36,.455,25.5,104.3,106.1,-1.8,18-16,12-20,8-3,24-20,L1,3-7,38.2,24.5%,60.9%
8,Miami,29,36,.446,26.0,109.9,110.6,-0.7,15-16,14-20,7-5,18-22,L5,3-7,38.5,29.8%,60.6%
9,Chicago,27,38,.415,28.0,116.6,120.3,-3.7,12-22,15-16,4-11,22-23,W3,5-5,31.7,0.0%,3.1%
10,Toronto,23,43,.348,32.5,110.8,115.7,-4.9,16-20,7-23,5-8,15-29,W2,6-4,28.2,0.0%,<1.0%
11,Brooklyn,22,43,.338,33.0,105.2,111.5,-6.3,10-21,12-22,3-8,12-28,L1,2-8,31.0,0.0%,2.4%
12,Philadelphia,22,43,.338,33.0,109.4,114.4,-5.0,12-21,10-22,3-11,14-27,L2,2-8,33.9,0.0%,23.6%
13,Charlotte,16,49,.246,39.0,105.4,113.0,-7.6,10-24,6-25,1-12,9-33,L1,2-8,24.1,0.0%,<1.0%
14,Washington,13,51,.203,41.5,108.3,120.6,-12.3,7-26,6-25,6-6,10-28,L2,4-6,15.6,0.0%,0.0%
0,Oklahoma City,54,12,.818,—,119.7,107.2,12.5,29-5,25-7,11-4,32-11,W1,8-2,66.1,100.0%,100.0%
1,Memphis,42,24,.636,12.0,122.6,116.7,5.9,24-10,18-14,10-5,25-16,W4,5-5,52.0,78.1%,99.8%
2,Denver,42,24,.636,12.0,121.1,116.6,4.5,22-10,20-14,7-6,25-15,L1,5-5,52.8,0.0%,100.0%
3,L.A. Lakers,40,23,.635,12.5,112.9,111.1,1.8,25-7,15-16,11-3,27-12,L2,8-2,46.1,38.6%,78.4%
4,Houston,41,25,.621,13.0,112.9,108.8,4.1,23-10,18-15,12-3,25-16,W4,6-4,48.7,21.5%,94.4%
5,Golden St.,37,28,.569,16.5,113.6,111.3,2.3,19-13,18-15,2-10,21-19,W5,9-1,44.6,11.8%,65.0%
6,Minnesota,38,29,.567,16.5,112.9,109.0,3.9,18-14,20-15,8-5,27-18,W6,7-3,45.8,0.0%,78.9%
7,L.A. Clippers,36,30,.545,18.0,111.1,108.9,2.2,22-10,14-20,7-7,21-22,W1,5-5,46.8,47.9%,85.7%
8,Sacramento,33,31,.516,20.0,116.6,115.2,1.4,16-15,17-16,4-8,23-21,L2,5-5,41.7,1.7%,31.5%
9,Dallas,33,34,.493,21.5,114.8,114.6,0.2,19-15,14-19,8-6,23-24,L1,2-8,43.8,0.0%,61.3%
10,Phoenix,30,36,.455,24.0,114.3,116.4,-2.1,18-13,12-23,8-4,20-24,L2,3-7,37.7,0.0%,3.5%
11,San Antonio,27,37,.422,26.0,113.8,116.1,-2.3,16-16,11-21,4-11,19-25,W1,3-7,35.9,0.0%,<1.0%
12,Portland,28,39,.418,26.5,110.6,114.6,-4.0,16-16,12-23,5-9,15-30,L5,4-6,32.4,0.0%,0.0%
13,New Orleans,18,48,.273,36.0,111.0,119.1,-8.1,12-21,6-27,3-12,12-32,W1,5-5,24.7,0.0%,0.0%
14,Utah,15,51,.227,39.0,112.5,119.8,-7.3,8-24,7-27,2-9,7-37,L7,1-9,24.3,0.0%,0.0%

In [ ]:
# Sort by PCT in Descending Order

df_combined = df_combined.sort_values(by = 'PCT', ascending = False)
df_combined

,Team,W,L,PCT,GB,PPG,OPPG,DIFF,HOME,ROAD,DIV,CONF,STRK,L10,W,DIV,POST
0,Cleveland,55,10,.846,—,122.7,111.4,11.3,30-4,25-6,11-1,38-7,W15,10-0,62.9,100.0%,100.0%
0,Oklahoma City,54,12,.818,—,119.7,107.2,12.5,29-5,25-7,11-4,32-11,W1,8-2,66.1,100.0%,100.0%
1,Boston,47,19,.712,8.5,116.8,108.3,8.5,23-12,24-7,11-2,32-11,L1,7-3,59.7,98.5%,100.0%
2,New York,42,23,.646,13.0,117.1,112.7,4.4,21-11,21-12,10-3,28-13,W2,5-5,52.2,1.5%,100.0%
2,Denver,42,24,.636,12.0,121.1,116.6,4.5,22-10,20-14,7-6,25-15,L1,5-5,52.8,0.0%,100.0%
1,Memphis,42,24,.636,12.0,122.6,116.7,5.9,24-10,18-14,10-5,25-16,W4,5-5,52.0,78.1%,99.8%
3,L.A. Lakers,40,23,.635,12.5,112.9,111.1,1.8,25-7,15-16,11-3,27-12,L2,8-2,46.1,38.6%,78.4%
4,Houston,41,25,.621,13.0,112.9,108.8,4.1,23-10,18-15,12-3,25-16,W4,6-4,48.7,21.5%,94.4%
5,Golden St.,37,28,.569,16.5,113.6,111.3,2.3,19-13,18-15,2-10,21-19,W5,9-1,44.6,11.8%,65.0%
6,Minnesota,38,29,.567,16.5,112.9,109.0,3.9,18-14,20-15,8-5,27-18,W6,7-3,45.8,0.0%,78.9%
3,Milwaukee,36,28,.563,18.5,114.6,112.5,2.1,22-11,14-17,6-7,26-19,L3,6-4,43.9,0.0%,88.5%
4,Indiana,36,28,.563,18.5,116.4,115.4,1.0,20-10,16-18,8-5,21-20,W1,5-5,46.0,0.0%,98.0%
5,Detroit,37,29,.561,18.5,114.8,112.9,1.9,18-14,19-15,4-9,25-20,W2,7-3,42.8,0.0%,88.6%
7,L.A. Clippers,36,30,.545,18.0,111.1,108.9,2.2,22-10,14-20,7-7,21-22,W1,5-5,46.8,47.9%,85.7%
8,Sacramento,33,31,.516,20.0,116.6,115.2,1.4,16-15,17-16,4-8,23-21,L2,5-5,41.7,1.7%,31.5%
9,Dallas,33,34,.493,21.5,114.8,114.6,0.2,19-15,14-19,8-6,23-24,L1,2-8,43.8,0.0%,61.3%
6,Atlanta,32,34,.485,23.5,117.4,119.6,-2.2,17-16,15-18,8-4,24-18,W4,6-4,39.0,45.7%,73.4%
7,Orlando,30,36,.455,25.5,104.3,106.1,-1.8,18-16,12-20,8-3,24-20,L1,3-7,38.2,24.5%,60.9%
10,Phoenix,30,36,.455,24.0,114.3,116.4,-2.1,18-13,12-23,8-4,20-24,L2,3-7,37.7,0.0%,3.5%
8,Miami,29,36,.446,26.0,109.9,110.6,-0.7,15-16,14-20,7-5,18-22,L5,3-7,38.5,29.8%,60.6%
11,San Antonio,27,37,.422,26.0,113.8,116.1,-2.3,16-16,11-21,4-11,19-25,W1,3-7,35.9,0.0%,<1.0%
12,Portland,28,39,.418,26.5,110.6,114.6,-4.0,16-16,12-23,5-9,15-30,L5,4-6,32.4,0.0%,0.0%
9,Chicago,27,38,.415,28.0,116.6,120.3,-3.7,12-22,15-16,4-11,22-23,W3,5-5,31.7,0.0%,3.1%
10,Toronto,23,43,.348,32.5,110.8,115.7,-4.9,16-20,7-23,5-8,15-29,W2,6-4,28.2,0.0%,<1.0%
12,Philadelphia,22,43,.338,33.0,109.4,114.4,-5.0,12-21,10-22,3-11,14-27,L2,2-8,33.9,0.0%,23.6%
11,Brooklyn,22,43,.338,33.0,105.2,111.5,-6.3,10-21,12-22,3-8,12-28,L1,2-8,31.0,0.0%,2.4%
13,New Orleans,18,48,.273,36.0,111.0,119.1,-8.1,12-21,6-27,3-12,12-32,W1,5-5,24.7,0.0%,0.0%
13,Charlotte,16,49,.246,39.0,105.4,113.0,-7.6,10-24,6-25,1-12,9-33,L1,2-8,24.1,0.0%,<1.0%
14,Utah,15,51,.227,39.0,112.5,119.8,-7.3,8-24,7-27,2-9,7-37,L7,1-9,24.3,0.0%,0.0%
14,Washington,13,51,.203,41.5,108.3,120.6,-12.3,7-26,6-25,6-6,10-28,L2,4-6,15.6,0.0%,0.0%

In [ ]:
# Reset Index

df_combined = df_combined.reset_index(drop = True)
df_combined

,Team,W,L,PCT,GB,PPG,OPPG,DIFF,HOME,ROAD,DIV,CONF,STRK,L10,W,DIV,POST
0,Cleveland,55,10,.846,—,122.7,111.4,11.3,30-4,25-6,11-1,38-7,W15,10-0,62.9,100.0%,100.0%
1,Oklahoma City,54,12,.818,—,119.7,107.2,12.5,29-5,25-7,11-4,32-11,W1,8-2,66.1,100.0%,100.0%
2,Boston,47,19,.712,8.5,116.8,108.3,8.5,23-12,24-7,11-2,32-11,L1,7-3,59.7,98.5%,100.0%
3,New York,42,23,.646,13.0,117.1,112.7,4.4,21-11,21-12,10-3,28-13,W2,5-5,52.2,1.5%,100.0%
4,Denver,42,24,.636,12.0,121.1,116.6,4.5,22-10,20-14,7-6,25-15,L1,5-5,52.8,0.0%,100.0%
5,Memphis,42,24,.636,12.0,122.6,116.7,5.9,24-10,18-14,10-5,25-16,W4,5-5,52.0,78.1%,99.8%
6,L.A. Lakers,40,23,.635,12.5,112.9,111.1,1.8,25-7,15-16,11-3,27-12,L2,8-2,46.1,38.6%,78.4%
7,Houston,41,25,.621,13.0,112.9,108.8,4.1,23-10,18-15,12-3,25-16,W4,6-4,48.7,21.5%,94.4%
8,Golden St.,37,28,.569,16.5,113.6,111.3,2.3,19-13,18-15,2-10,21-19,W5,9-1,44.6,11.8%,65.0%
9,Minnesota,38,29,.567,16.5,112.9,109.0,3.9,18-14,20-15,8-5,27-18,W6,7-3,45.8,0.0%,78.9%
10,Milwaukee,36,28,.563,18.5,114.6,112.5,2.1,22-11,14-17,6-7,26-19,L3,6-4,43.9,0.0%,88.5%
11,Indiana,36,28,.563,18.5,116.4,115.4,1.0,20-10,16-18,8-5,21-20,W1,5-5,46.0,0.0%,98.0%
12,Detroit,37,29,.561,18.5,114.8,112.9,1.9,18-14,19-15,4-9,25-20,W2,7-3,42.8,0.0%,88.6%
13,L.A. Clippers,36,30,.545,18.0,111.1,108.9,2.2,22-10,14-20,7-7,21-22,W1,5-5,46.8,47.9%,85.7%
14,Sacramento,33,31,.516,20.0,116.6,115.2,1.4,16-15,17-16,4-8,23-21,L2,5-5,41.7,1.7%,31.5%
15,Dallas,33,34,.493,21.5,114.8,114.6,0.2,19-15,14-19,8-6,23-24,L1,2-8,43.8,0.0%,61.3%
16,Atlanta,32,34,.485,23.5,117.4,119.6,-2.2,17-16,15-18,8-4,24-18,W4,6-4,39.0,45.7%,73.4%
17,Orlando,30,36,.455,25.5,104.3,106.1,-1.8,18-16,12-20,8-3,24-20,L1,3-7,38.2,24.5%,60.9%
18,Phoenix,30,36,.455,24.0,114.3,116.4,-2.1,18-13,12-23,8-4,20-24,L2,3-7,37.7,0.0%,3.5%
19,Miami,29,36,.446,26.0,109.9,110.6,-0.7,15-16,14-20,7-5,18-22,L5,3-7,38.5,29.8%,60.6%
20,San Antonio,27,37,.422,26.0,113.8,116.1,-2.3,16-16,11-21,4-11,19-25,W1,3-7,35.9,0.0%,<1.0%
21,Portland,28,39,.418,26.5,110.6,114.6,-4.0,16-16,12-23,5-9,15-30,L5,4-6,32.4,0.0%,0.0%
22,Chicago,27,38,.415,28.0,116.6,120.3,-3.7,12-22,15-16,4-11,22-23,W3,5-5,31.7,0.0%,3.1%
23,Toronto,23,43,.348,32.5,110.8,115.7,-4.9,16-20,7-23,5-8,15-29,W2,6-4,28.2,0.0%,<1.0%
24,Philadelphia,22,43,.338,33.0,109.4,114.4,-5.0,12-21,10-22,3-11,14-27,L2,2-8,33.9,0.0%,23.6%
25,Brooklyn,22,43,.338,33.0,105.2,111.5,-6.3,10-21,12-22,3-8,12-28,L1,2-8,31.0,0.0%,2.4%
26,New Orleans,18,48,.273,36.0,111.0,119.1,-8.1,12-21,6-27,3-12,12-32,W1,5-5,24.7,0.0%,0.0%
27,Charlotte,16,49,.246,39.0,105.4,113.0,-7.6,10-24,6-25,1-12,9-33,L1,2-8,24.1,0.0%,<1.0%
28,Utah,15,51,.227,39.0,112.5,119.8,-7.3,8-24,7-27,2-9,7-37,L7,1-9,24.3,0.0%,0.0%
29,Washington,13,51,.203,41.5,108.3,120.6,-12.3,7-26,6-25,6-6,10-28,L2,4-6,15.6,0.0%,0.0%

## Conclusion

This notebook successfully scraped NBA team standings data for both the Eastern and Western Conferences from CBS Sports. The data was then cleaned, combined, and sorted by winning percentage to provide a unified view of team performance across the league.

In [ ]:
# Great Job!